---
title: "KNN"
author: "Yi Zhang"
date: "2023-08-20"
output: html_document
---

```{r}
library(class)
library(kknn)
library(e1071)
library(caret)
library(MASS)
library(reshape2)
library(ggplot2)
library(kernlab)
```

```{r}
data(Pima.tr)
str(Pima.tr)
```

```{r}
data(Pima.te)
str(Pima.te)
```

```{r}
pima <- rbind(Pima.tr, Pima.te)
pima.melt <- melt(pima, id.var = "type")
```

```{r}
ggplot(data = pima.melt, aes(x = type, y = value)) + geom_boxplot() + 
  facet_wrap(~ variable, ncol = 2)
```

```{r}
pima.scale <- data.frame(scale(pima[, -8]))
pima.scale$type <- pima$type
pima.scale.melt <- melt(pima.scale, id.var = "type")
ggplot(data = pima.melt, aes(x = type, y = value)) + geom_boxplot() + 
  facet_wrap(~ variable, ncol = 2)
```

```{r}
cor(pima.scale[-8])
```

```{r}
set.seed(1)
ind <- sample(2, nrow(pima.scale), replace = TRUE, prob = c(0.7, 0.3))
train <- pima.scale[ind == 1,]
test <- pima.scale[ind == 2,]
```

```{r}
grid1 <- expand.grid(k = seq(2, 20, by = 1))
control <- trainControl(method = 'cv')
set.seed(820)
knn.train <- train(type ~ ., data = train, method = "knn", trControl = control,
                   tuneGrid = grid1)
knn.train
```

```{r}
knn.test <- knn(train[,-8], test[,-8], train[, 8], k = 16)
table(knn.test, test$type)
```

```{r}
set.seed(820)
kknn.train <- train.kknn(type ~ ., data = train, kmax = 25, distance = 2, 
                         kernel = c("rectangular", "triangular", "epanechnikov"))
plot(kknn.train)
```

```{r}
kknn.train
```

```{r}
kknn.pred <- predict(kknn.train, newdata = test)
table(kknn.pred, test$type)
```
