---
title: "SVM"
author: "Yi Zhang"
date: "2023-08-20"
output: html_document
---

```{r}
library(class)
library(kknn)
library(e1071)
library(caret)
library(MASS)
library(reshape2)
library(ggplot2)
library(kernlab)
```

```{r}
pima <- rbind(Pima.tr, Pima.te)
pima.scale <- data.frame(scale(pima[, -8]))
pima.scale$type <- pima$type
pima.scale.melt <- melt(pima.scale, id.var = "type")
set.seed(1)
ind <- sample(2, nrow(pima.scale), replace = TRUE, prob = c(0.7, 0.3))
train <- pima.scale[ind == 1,]
test <- pima.scale[ind == 2,]
```

tune.svm可以选择最佳核函数和参数
```{r tune.svm}
linear.tune <- tune.svm(type ~ ., data = train, kernel = "linear", 
                        cost = c(0.001, 0.01, 0.1, 1, 5, 10))
summary(linear.tune)
```

```{r linear}
best.linear <- linear.tune$best.model
tune.test <- predict(best.linear, newdata = test)
table(tune.test, test$type)
```

```{r polynomial}
set.seed(820)
poly.tune <- tune.svm(type ~ ., data = train, kernel = "polynomial",
                      degree = c(3, 4, 5), 
                     coef0 = c(0.1, 0.5, 1, 2, 3, 4))
summary(poly.tune)
best.poly <- poly.tune$best.model
poly.test <- predict(best.poly, newdata = test)
table(poly.test, test$type)
# View(poly.tune)
```


```{r radial}
set.seed(820)
rbf.tune <- tune.svm(type ~ ., data = train, kernel = "radial",
                     gamma = c(0.1, 0.5, 1, 2, 3, 4))
summary(rbf.tune)
best.rbf <- rbf.tune$best.model
rbf.test <- predict(best.rbf, newdata = test)
table(rbf.test, test$type)
```

```{r sigmoid}
set.seed(820)
sigmoid.tune <- tune.svm(type ~ ., data = train, kernel = "sigmoid",
                     gamma = c(0.1, 0.5, 1, 2, 3, 4),
                     coef0 = c(0.1, 0.5, 1, 2, 3, 4))
summary(sigmoid.tune)
best.sigmoid <- sigmoid.tune$best.model
sigmoid.test <- predict(best.sigmoid, newdata = test)
table(sigmoid.test, test$type)
```

```{r}
confusionMatrix(sigmoid.test, test$type, positive = "Yes")
```
SVM中的特征选择
```{r}
rfeCNTL <- rfeControl(functions = lrFuncs, method = "cv", number = 10)
svm.features <- rfe(train[, 1:7], train[,8], sizes = c(7, 6, 5, 4),
                    rfeControl = rfeCNTL, method = "svmLinear")  # svmPoly
svm.features
```

```{r}
svm.5 <- svm(type ~ glu+ ped + npreg + bmi + age, data = train, kernel = "linear")
svm.5.predict <- predict(svm.5, newdata = test[c(1, 2, 5, 6, 7)])
table(svm.5.predict, test$type)
confusionMatrix(svm.5.predict, test$type, positive = "Yes")
```



